#import "./ImageFragment.gql"

fragment AboutFragment on AboutRecord {
	id
	title
	intro
  slug
	content {
    value
		blocks {
			... on ImageRecord {
				__typename
				id
				image {
					...ImageFragment
				}
			}
		}
	}
}
