#import "./ImageFragment.gql"
#import "./VideoFragment.gql"
#import "./RegionFragment.gql"

fragment CommissionFragment on CommissionRecord {
	id
	title
	intro
	slug
	city
	year
	artist
	consultant
	blackHeadline
	image {
		...ImageFragment
	}
	category {
		id
		title
	}
	content {
		... on ImageRecord {
			__typename
			id
			image {
				...ImageFragment
			}
		}
		... on VideoRecord {
			__typename
			id
			video {
				height
				width
				title
				provider
				providerUid
				thumbnailUrl
				url
			}
		}
		... on RecordInterface {
			__typename
			id
		}
	}
	region {
		...RegionFragment
	}
}
