#import "./ImageThumbnailFragment.gql"
#import "./RegionFragment.gql"

fragment CommissionFragmentLight on CommissionRecord {
	id
	title
	slug
	image {
		...ImageThumbnailFragment
	}
	category {
		id
		title
	}
	region {
		...RegionFragment
	}
}
