#import "./RegionFragment.gql"

fragment MemberLightFragment on MemberRecord {
	__typename
	id
	firstName
	lastName
	fullName
	email
	region {
		...RegionFragment
	}
	image {
		...ImageThumbnailFragment
	}
	slug
	_status
	_firstPublishedAt
}
