#import "./RegionFragment.gql"

fragment MemberFragment on MemberRecord {
	__typename
	_modelApiKey
	id
	firstName
	lastName
	fullName
	email
	bio(markdown: false)
	yearOfBirth
	birthPlace
	city
	webpage
	instagram
	memberCategory {
		id
		categoryType
	}
	region {
		...RegionFragment
	}
	image {
		...ImageThumbnailFragment
	}
	content {
		... on ImageRecord {
			__typename
			id
			image {
				...ImageFragment
			}
		}
		... on VideoRecord {
			__typename
			id
			video {
				height
				width
				title
				provider
				providerUid
				thumbnailUrl
				url
			}
		}
		... on RecordInterface {
			__typename
			id
		}
	}
	slug
	_status
	_firstPublishedAt
}
