#import "./ImageThumbnailFragment.gql"
#import "./VideoFragment.gql"
#import "./RegionFragment.gql"

fragment MemberNewsLightFragment on MemberNewsRecord {
	__typename
	id
	createdAt
	title
	image {
		...ImageThumbnailFragment
	}
	intro(markdown: false)
	category {
		id
		category
	}
	date
	location
	slug
	region {
		...RegionFragment
	}
}
