#import "./ImageFragment.gql"
#import "./RegionFragment.gql"

fragment NewsFragment on NewsRecord {
	id
	title
	slug
	intro
	createdAt
	image {
		...ImageFragment
	}
	region {
		...RegionFragment
	}
	content {
		value
		blocks
	}
}
