#import "./fragments/AboutFragment.gql"

query About($slug: String!) {
	about(filter: { slug: { eq: $slug } }) {
		...AboutFragment
	}
}

query AllAbouts {
	abouts: allAbouts {
		...AboutFragment
	}
}
