#import "./fragments/ImageFragment.gql"

query About {
  about {
    title
    id
    content {
      blocks {
        ... on ImageRecord {
          __typename
          id
          image{
            ...ImageFragment
          }
        }
      }
      value
    }
  }
}

query AllAbouts {
  abouts : allAbouts {
    title
    id
    content {
      blocks {
        ... on ImageRecord {
          __typename
          id
          image{
            ...ImageFragment
          }
        }
      }
      value
    }
  }
}
