#import "./fragments/CommissionFragment.gql"

query Commission($slug: String!) {
	commission(filter: { slug: { eq: $slug } }) {
		...CommissionFragment
	}
}

query AllCommissions {
	commissions: allCommissions {
		...CommissionFragment
	}
}

query AllCommissionsMenu {
	commissions: allCommissions {
		title
		slug
	}
}

query AllCommissionCategories {
	commissionCategories: allCommissionCategories {
		id
		title
	}
}
