#import "./fragments/ConsultFragment.gql"

query Consult($slug: String!) {
	consult(filter: { slug: { eq: $slug } }) {
		...ConsultFragment
	}
}

query AllConsults {
	consults: allConsults(first: 100) {
		...ConsultFragment
	}
}

query AllConsultsMenu {
	consults: allConsults(first: 100) {
		title
		slug
	}
}

query AllConsultants {
	consultants: allConsultants(first: 100) {
		id
		email
		name
		title
	}
}
