#import "./fragment/MemberFragment.gql"
#import "./fragment/MemberFragmentLight.gql"
#import "./fragment/MemberNewsFragment.gql"

query AllMembers {
	members: allMembers {
		...MemberFragmentLight
	}
}
query AllMembersWithPortfolio($regionId: ItemId) {
	members: allMembers(filter: { image: { exists: true }, region: { eq: $regionId } }) {
		...MemberFragmentLight
	}
}

query AllMembersCities {
	cities: allMembers(filter: { image: { exists: true } }) {
		name: city
	}
}

query Member($email: String!) {
	member(filter: { email: { eq: $email } }) {
		...MemberFragment
	}
}
query MemberBySlug($slug: String!) {
	member(filter: { slug: { eq: $slug } }) {
		...MemberFragment
	}
}

query MemberByPasswordToken($token: String!) {
	member(filter: { resettoken: { eq: $token } }) {
		id
		email
		firstName
		lastName
	}
}

query AllMemberCategories {
	memberCategories: allMemberCategories {
		id
		categoryType
	}
}

query AllMemberNews {
	memberNews: allMemberNews {
		...MemberNewsFragment
	}
}
