#import "./fragments/ImageFragment.gql"
#import "./fragments/NewsFragment.gql"

query AllNews($first: IntType = 10, $skip: IntType = 0) {
	news: allNews(orderBy: [createdAt_DESC], first: $first, skip: $skip) {
		...NewsFragment
	}
	pagination: _allNewsMeta {
		count
	}
}

query News($id: ItemId!) {
	news(filter: { id: { eq: $id } }) {
		...NewsFragment
	}
}
