#import "./fragments/ImageFragment.gql"
#import "./freagments/ProjectFragment.gql"

query AllProjects {
	projects: allProjects {
		...ProjectFragment
	}
}

query ProjectsIntro {
	introInitiative {
		intro(markdown: false)
	}
}
