#import "./fragments/ImagaFragment.gql"
#import "./fragments/ImagaThumbnailFragment.gql"
#import "./fragments/RegionFragment.gql"
#import "./fragments/CommissionsFragment.gql"
#import "./fragments/MemberLightFragment.gql"

query Region($regionId: ItemId) {
	region(filter: { id: { eq: $regionId } }) {
		__typename
		id
		name
		slug
		gallery {
			id
			headline
			image {
				...ImageFragment
			}
			link {
				__typename
				... on CommissionRecord {
					id
					title
					slug
					image {
						...ImageFragment
					}
				}
				... on ForArtistRecord {
					id
					title
					slug
					image {
						...ImageFragment
					}
				}
				... on MemberNewsRecord {
					id
					title
					slug
					image {
						...ImageFragment
					}
				}
				... on NewsRecord {
					id
					title
					slug
					image {
						...ImageFragment
					}
				}
			}
		}
		sections {
			... on ImageShortcutRecord {
				id
				headline
				image {
					...ImageFragment
				}
				text
				link
				text
			}
			... on LatestNewsRecord {
				id
				description
			}
			... on LatestMemberNewsRecord {
				id
			}
			... on TextRecord {
				id
				url
				headline
				text(markdown: false)
			}
			... on SelectedCommissionRecord {
				commissions {
					...CommissionFragment
				}
			}
			... on SelectedMemberRecord {
				selectedMembers {
					...MemberLightFragment
				}
			}
		}
	}
}

query RegionMeta($regionId: ItemId) {
	region(filter: { id: { eq: $regionId } }) {
		contactIntro(markdown: false)
		info {
			title
			text
		}
	}
	employees: allEmployees(filter: { region: { eq: $regionId } }) {
		name
		email
		image {
			...ImageThumbnailFragment
		}
		region {
			...RegionFragment
		}
	}
}
