#import "./fragments/ImagaFragment.gql"
#import "./fragments/CommissionsFragment.gql"

query Region($regionId: ItemId!) {
	region(filter: { id: { eq: $regionId } }) {
		id
		name
		slug
		sections {
			... on FindArtistRecord {
				id
			}
			... on ImageShortcutRecord {
				id
				headline
				image {
					...ImageFragment
				}
				text
				link {
					__typename
					... on CommissionRecord {
						id
					}
					... on ForArtistRecord {
						id
					}
					... on MembersNewsRecord {
						id
					}
					... on NewsRecord {
						id
					}
				}
				text
			}
			... on LatestNewsRecord {
				id
				description
			}
			... on LatestMemberNewsRecord {
				id
			}
			... on TextRecord {
				id
				url
				headline
				text(markdown: false)
			}
			... on SelectedCommissionRecord {
				commissions {
					...CommissionFragment
				}
			}
		}
	}
}
