#import "./fragments/MemberLightFragment"

query SiteSearch($memberIds: [ItemId], $first: IntType = 100) {
	members: allMembers(first: $first, filter: { id: { in: $memberIds } }) {
		...MemberLightFragment
	}
}
