#import "./fragments/ImageThumbnailFragment"

query SiteSearch(
	$memberIds: [ItemId]
	$newsIds: [ItemId]
	$memberNewsIds: [ItemId]
	$first: IntType = 100
) {
	members: allMembers(first: $first, filter: { id: { in: $memberIds } }) {
		__typename
		_modelApiKey
		fullName
		bio(markdown: false)
		slug
		image {
			...ImageThumbnailFragment
		}
	}
	news: allNews(first: $first, filter: { id: { in: $newsIds } }) {
		__typename
		_modelApiKey
		title
		intro(markdown: false)
		slug
		image {
			...ImageThumbnailFragment
		}
	}
	memberNews: allMemberNews(first: $first, filter: { id: { in: $memberNewsIds } }) {
		__typename
		_modelApiKey
		title
		intro(markdown: false)
		slug
		image {
			...ImageThumbnailFragment
		}
	}
}
